/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barruzzo;

import barruzzo.model.Cliente;
import barruzzo.model.Ordinazione;
import barruzzo.model.Prodotto;
import java.util.ArrayList;

/**
 *
 * @author Studente
 */
public class frmCliente extends javax.swing.JFrame {

    ArrayList listaprodotti; //di prodotti
    ArrayList listaclassi;
    ArrayList listaordinazioni;
    ArrayList listaclienti;

    Cliente clienteCorrente;

    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();

        Singleton singleton = Singleton.getInstance();
        listaprodotti = singleton.getListaprodotti();
        listaclassi = singleton.getListaclassi();
        listaordinazioni = singleton.getListaordinazioni();
        listaclienti = singleton.getListaclienti();

        pnlCliente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        btnAccedi = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        pnlCliente = new javax.swing.JPanel();
        btnStampaProdotti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaStampa = new javax.swing.JTextArea();
        btnStampaOrdinazioni = new javax.swing.JButton();
        btnStampaOrdinazioniClasse = new javax.swing.JButton();
        btnInserisciOrdinazione = new javax.swing.JButton();
        txtIdProdotto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCliente.setText("Cliente");

        pnlLogin.setBackground(new java.awt.Color(255, 153, 153));
        pnlLogin.setForeground(new java.awt.Color(255, 204, 204));

        txtEmail.setText("txtEmail");

        btnAccedi.setText("Accedi");
        btnAccedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccediActionPerformed(evt);
            }
        });

        txtPassword.setText("txtPassword");

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAccedi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccedi))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCliente.setBackground(new java.awt.Color(153, 153, 255));

        btnStampaProdotti.setText("StampaProdotti");
        btnStampaProdotti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampaProdottiActionPerformed(evt);
            }
        });

        txtaStampa.setColumns(20);
        txtaStampa.setRows(5);
        jScrollPane1.setViewportView(txtaStampa);

        btnStampaOrdinazioni.setText("StampaOrdinazioni");
        btnStampaOrdinazioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampaOrdinazioniActionPerformed(evt);
            }
        });

        btnStampaOrdinazioniClasse.setText("StampaOrdinazioniClasse");
        btnStampaOrdinazioniClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampaOrdinazioniClasseActionPerformed(evt);
            }
        });

        btnInserisciOrdinazione.setText("InserisciOrdinazione");
        btnInserisciOrdinazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciOrdinazioneActionPerformed(evt);
            }
        });

        txtIdProdotto.setText("txtIdProdotto");

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(btnInserisciOrdinazione)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnStampaOrdinazioni)
                    .addComponent(btnStampaProdotti)
                    .addComponent(btnStampaOrdinazioniClasse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnStampaProdotti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStampaOrdinazioni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStampaOrdinazioniClasse)
                        .addGap(15, 15, 15)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInserisciOrdinazione)
                            .addComponent(txtIdProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStampaProdottiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampaProdottiActionPerformed
        txtaStampa.setText("");
        stampa();
    }//GEN-LAST:event_btnStampaProdottiActionPerformed

    private void btnAccediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccediActionPerformed
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        for (int i = 0; i < listaclienti.size(); i++) {
            Cliente cliente = (Cliente) listaclienti.get(i);
            if (email.equals(cliente.getEmail()) && password.equals(cliente.getPassword())) {
                pnlCliente.setVisible(true);
                pnlLogin.setVisible(false);
                lblCliente.setText("Cliente: " + email);
                txtaStampa.setText(email);
                clienteCorrente = cliente;
            }
        }
    }//GEN-LAST:event_btnAccediActionPerformed

    private void btnStampaOrdinazioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampaOrdinazioniActionPerformed
        float somma = 0;
        txtaStampa.setText("");
        for (int i = 0; i < listaordinazioni.size(); i++) {
            Ordinazione ordinazione = (Ordinazione) listaordinazioni.get(i);
            if (clienteCorrente.getIdCliente() == ordinazione.getCliente().getIdCliente()) {
                txtaStampa.append(ordinazione.toString() + "\n");
                somma = somma + ordinazione.getProdotto().getPrezzo();
            }
        }
        txtaStampa.append("Totale:" + somma + "\n");
      }//GEN-LAST:event_btnStampaOrdinazioniActionPerformed

    private void btnStampaOrdinazioniClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampaOrdinazioniClasseActionPerformed
        float somma = 0;
        txtaStampa.setText("");
        String classe = clienteCorrente.getClasse().getNome();
        for (int i = 0; i < listaordinazioni.size(); i++) {
            Ordinazione ordinazione = (Ordinazione) listaordinazioni.get(i);
            if (ordinazione.getCliente().getClasse().getNome().equals(classe)) {
                txtaStampa.append(ordinazione.toString() + "\n");
                somma = somma + ordinazione.getProdotto().getPrezzo();
            }
        }
        txtaStampa.append("Totale:" + somma + "\n");
    }//GEN-LAST:event_btnStampaOrdinazioniClasseActionPerformed

    private void btnInserisciOrdinazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciOrdinazioneActionPerformed
        int idProdotto = Integer.valueOf(txtIdProdotto.getText());
        Prodotto prodotto = cercaProdottoById(idProdotto);
        Ordinazione ordinazione= new Ordinazione(clienteCorrente, prodotto);
        listaordinazioni.add(ordinazione);
    }//GEN-LAST:event_btnInserisciOrdinazioneActionPerformed

    private Prodotto cercaProdottoById(int idProdotto) {
        for (int i = 0; i < listaprodotti.size(); i++) {
            Prodotto prodotto = (Prodotto) listaprodotti.get(i);
            if (prodotto.getIdProdotto() == idProdotto) {
                return prodotto;
            }
        }
        return null;
    }

    private void stampa() {
        for (int i = 0; i < listaprodotti.size(); i++) {
            Prodotto prodotto = (Prodotto) listaprodotti.get(i);
            txtaStampa.append(prodotto.toString() + "\n");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccedi;
    private javax.swing.JButton btnInserisciOrdinazione;
    private javax.swing.JButton btnStampaOrdinazioni;
    private javax.swing.JButton btnStampaOrdinazioniClasse;
    private javax.swing.JButton btnStampaProdotti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdProdotto;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextArea txtaStampa;
    // End of variables declaration//GEN-END:variables
}
