package agenda;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;
import nu.xom.ParsingException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author L14_00
 */
public class frmAgenda extends javax.swing.JFrame {

    ArrayList<Persona> listarella;// = new ArrayList<Integer>();

    /**
     * Creates new form frmRicerca
     */
    public frmAgenda() {
        initComponents();
        listarella = new ArrayList<Persona>();
        /*
        txtA.setText("");
        txtRisultato.setText("");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnAggiungi = new javax.swing.JButton();
        btnOrdina = new javax.swing.JButton();
        btnCancella = new javax.swing.JButton();
        btnRicerca = new javax.swing.JButton();
        txtCognome = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnGeneraXML = new javax.swing.JButton();
        btnStampaPersonaCasuale = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGeneraNumero = new javax.swing.JButton();
        btnGeneraXMLXom = new javax.swing.JButton();
        btnStampaSuFile = new javax.swing.JButton();
        btnImportaXMLXom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.setText("txtNome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setText("txtArea");
        jScrollPane1.setViewportView(txtArea);

        btnAggiungi.setText("btnAggiungi");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        btnOrdina.setText("btnOrdina");
        btnOrdina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdinaActionPerformed(evt);
            }
        });

        btnCancella.setText("btnCancella");
        btnCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellaActionPerformed(evt);
            }
        });

        btnRicerca.setText("btnRicerca");
        btnRicerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRicercaActionPerformed(evt);
            }
        });

        txtCognome.setText("txtCognome");
        txtCognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCognomeActionPerformed(evt);
            }
        });

        txtNumero.setText("txtNumero");
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        btnGeneraXML.setText("btnGeneraXML");
        btnGeneraXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraXMLActionPerformed(evt);
            }
        });

        btnStampaPersonaCasuale.setText("btnStampaPersonaCasuale");
        btnStampaPersonaCasuale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampaPersonaCasualeActionPerformed(evt);
            }
        });

        jLabel1.setText("nome");

        jLabel2.setText("cognome");

        jLabel3.setText("numero");

        btnGeneraNumero.setText("btnGeneraNumero");
        btnGeneraNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraNumeroActionPerformed(evt);
            }
        });

        btnGeneraXMLXom.setText("btnGeneraXMLXom");
        btnGeneraXMLXom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraXMLXomActionPerformed(evt);
            }
        });

        btnStampaSuFile.setText("btnStampaSuFile");
        btnStampaSuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampaSuFileActionPerformed(evt);
            }
        });

        btnImportaXMLXom.setText("btnImportaXMLXom");
        btnImportaXMLXom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportaXMLXomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGeneraNumero))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnImportaXMLXom)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAggiungi)
                            .addComponent(btnOrdina)
                            .addComponent(btnCancella)
                            .addComponent(btnGeneraXML)
                            .addComponent(btnRicerca)
                            .addComponent(btnStampaPersonaCasuale)
                            .addComponent(btnGeneraXMLXom)
                            .addComponent(btnStampaSuFile))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAggiungi)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOrdina)
                            .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancella)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRicerca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGeneraXML)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStampaPersonaCasuale)
                            .addComponent(btnGeneraNumero))
                        .addGap(27, 27, 27)
                        .addComponent(btnGeneraXMLXom)
                        .addGap(18, 18, 18)
                        .addComponent(btnStampaSuFile))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnImportaXMLXom)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void stampaListarella() {
        txtArea.setText("");
        for (int i = 0; i < listarella.size(); i++) {
            txtArea.append("" + listarella.get(i) + "\n");
        }
    }
    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        // TODO add your handling code here:
        String nome, cognome, numero;

        nome = txtNome.getText();
        cognome = txtCognome.getText();
        numero = txtNumero.getText();
        Persona persona = new Persona(nome, cognome, numero);
        listarella.add(persona);
        stampaListarella();
    }//GEN-LAST:event_btnAggiungiActionPerformed

    private void btnOrdinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdinaActionPerformed
        Collections.sort(listarella);
        stampaListarella();
    }//GEN-LAST:event_btnOrdinaActionPerformed

    private void btnCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellaActionPerformed
        String nome = txtNome.getText();
        String cognome = txtCognome.getText();
        String numero = txtNumero.getText();
        int i;
        for (i = 0; i < listarella.size(); i++) {
            Persona persona = listarella.get(i);
            if (persona.nome.equals(nome)
                    && persona.cognome.equals(cognome)
                    && persona.numero.equals(numero)) {
                listarella.remove(i);
                break;
            }
        }
        stampaListarella();
    }//GEN-LAST:event_btnCancellaActionPerformed

    private void btnRicercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRicercaActionPerformed
        String nome = txtNome.getText();
        String cognome = txtCognome.getText();
        String numero = txtNumero.getText();
        int i;
        boolean trovato = false;
        for (i = 0; i < listarella.size(); i++) {
            Persona persona = listarella.get(i);
            if (persona.nome.equals(nome)
                    && persona.cognome.equals(cognome)
                    && persona.numero.equals(numero)) {
                trovato = true;
                break;
            }
        }
        if (trovato) {
            txtArea.setText("trovato");
        } else {
            txtArea.setText("non trovato");
        }
    }//GEN-LAST:event_btnRicercaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCognomeActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnGeneraXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraXMLActionPerformed
        txtArea.setText("<?xml version=\"1.0\"?>\n");
        txtArea.append("<agenda>\n");

        for (int i = 0; i < listarella.size(); i++) {
            Persona persona = listarella.get(i);
            txtArea.append("<persona>\n");
            txtArea.append("<nome>" + persona.nome + "</nome>\n");
            txtArea.append("<cognome>" + persona.cognome + "</cognome>\n");
            txtArea.append("<numero>" + persona.numero + "</numero>\n");
            txtArea.append("</persona>\n");
        }
        txtArea.append("</agenda>\n");

    }//GEN-LAST:event_btnGeneraXMLActionPerformed

    private void btnStampaPersonaCasualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampaPersonaCasualeActionPerformed
        if (listarella.size() > 0) {
            Random random = new Random();
            int casuale = random.nextInt(listarella.size());
            Persona personaCasuale = listarella.get(casuale);
            txtArea.setText("" + personaCasuale + "\n");
        }
    }//GEN-LAST:event_btnStampaPersonaCasualeActionPerformed

    private void btnGeneraNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraNumeroActionPerformed
        ///33333
        ///99999
        Random random = new Random();
        int casuale = random.nextInt(99999 - 33333) + 33333;
        txtNumero.setText("" + casuale);


    }//GEN-LAST:event_btnGeneraNumeroActionPerformed

    private void btnGeneraXMLXomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraXMLXomActionPerformed
        // TODO add your handling code here:

        Element agenda = new Element("agenda");
        for (int i = 1; i < listarella.size(); i++) {
            Element persona = new Element("persona");
            Persona p = listarella.get(i);

            Element nome = new Element("nome");
            nome.appendChild(p.nome);

            Element cognome = new Element("cognome");
            cognome.appendChild(p.cognome);

            Element numero = new Element("numero");
            numero.appendChild(p.numero);

            persona.appendChild(nome);
            persona.appendChild(cognome);
            persona.appendChild(numero);

            agenda.appendChild(persona);
        }
        Document doc = new Document(agenda);
        txtArea.setText(doc.toXML());
    }//GEN-LAST:event_btnGeneraXMLXomActionPerformed

    private void btnStampaSuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampaSuFileActionPerformed
        try {
            //FileWriter fileWriter = new FileWriter("c:\\prova\\MiaAgenda.txt", true);
            FileWriter fileWriter = new FileWriter("MiaAgenda.txt", false);
            PrintWriter printWriter = new PrintWriter(fileWriter);
            printWriter.print(txtArea.getText());
            printWriter.print("con orgoglio fatto con printwriter");
            printWriter.close();
            fileWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(frmAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnStampaSuFileActionPerformed

    private void btnImportaXMLXomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportaXMLXomActionPerformed
        listarella.removeAll(listarella);
        Builder builder = new Builder();

        try {
            //Document doc = builder.build(txtArea.getText().toString());
            Document doc = builder.build(new StringReader(txtArea.getText()));

            // txtArea.setText("");
            Element agenda = doc.getRootElement();
            Elements persone = agenda.getChildElements("persona");
            for (int i = 0; i < persone.size(); i++) {
                Element persona = persone.get(i);
                Element nome = persona.getFirstChildElement("nome");
                Element cognome = persona.getFirstChildElement("cognome");
                Element numero = persona.getFirstChildElement("numero");
                // txtArea.setText(" ew ew w" + cognome + "dfsdsd" + nome + "fdsfdf" + numero);
                listarella.add(new Persona(nome.getValue(), cognome.getValue(), numero.getValue()));
            }
        } catch (ParsingException ex) {
            Logger.getLogger(frmAgenda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        stampaListarella();
// TODO add your handling code here:
    }//GEN-LAST:event_btnImportaXMLXomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnCancella;
    private javax.swing.JButton btnGeneraNumero;
    private javax.swing.JButton btnGeneraXML;
    private javax.swing.JButton btnGeneraXMLXom;
    private javax.swing.JButton btnImportaXMLXom;
    private javax.swing.JButton btnOrdina;
    private javax.swing.JButton btnRicerca;
    private javax.swing.JButton btnStampaPersonaCasuale;
    private javax.swing.JButton btnStampaSuFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
