/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ricercaauto;

import java.util.ArrayList;

/**
 *
 * @author L14_00
 */
public class frmRicercaAuto extends javax.swing.JFrame {

    /**
     * Creates new form frmRicercaAuto
     */
    ArrayList listaauto;

    public frmRicercaAuto() {
        initComponents();
        listaauto = new ArrayList();
        pulisci();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdAutomobile = new javax.swing.JTextField();
        txtModello = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtCarrozzeria = new javax.swing.JTextField();
        txtAlimentazione = new javax.swing.JTextField();
        txtCilindrata = new javax.swing.JTextField();
        txtPotenza = new javax.swing.JTextField();
        txtPrezzo = new javax.swing.JTextField();
        bntInserisci = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaStampa = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bntStampa = new javax.swing.JButton();
        btnPulisci = new javax.swing.JButton();
        btnCerca = new javax.swing.JButton();
        btnCancella = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdAutomobile.setText("txtIdAutomobile");

        txtModello.setText("txtModello");

        txtMarca.setText("txtMarca");

        txtCarrozzeria.setText("txtCarrozzeria");

        txtAlimentazione.setText("txtAlimentazione");

        txtCilindrata.setText("txtCilindrata");

        txtPotenza.setText("txtPotenza");

        txtPrezzo.setText("txtPrezzo");
        txtPrezzo.setVerifyInputWhenFocusTarget(false);

        bntInserisci.setText("Inserisci");
        bntInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInserisciActionPerformed(evt);
            }
        });

        txtaStampa.setColumns(20);
        txtaStampa.setRows(5);
        txtaStampa.setText("txtaStampa\n");
        jScrollPane1.setViewportView(txtaStampa);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("idAutomobile");

        jLabel2.setText("modello");

        jLabel3.setText("marca");

        jLabel4.setText("carrozzeria");

        jLabel5.setText("alimentazione");

        jLabel6.setText("cilindrata");

        jLabel7.setText("potenza");

        jLabel8.setText("prezzo");

        bntStampa.setText("Stampa");
        bntStampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntStampaActionPerformed(evt);
            }
        });

        btnPulisci.setText("Pulisci");
        btnPulisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulisciActionPerformed(evt);
            }
        });

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        btnCancella.setText("Cancella");
        btnCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellaActionPerformed(evt);
            }
        });

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPotenza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCilindrata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlimentazione, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarrozzeria, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdAutomobile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModello, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrezzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntInserisci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPulisci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancella))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntStampa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifica)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAutomobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntInserisci)
                    .addComponent(jLabel1)
                    .addComponent(btnPulisci)
                    .addComponent(btnCancella))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarrozzeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlimentazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPotenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntStampa)
                            .addComponent(btnCerca)
                            .addComponent(btnModifica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInserisciActionPerformed

        //txtaStampa.setText("ciao \n");
        int idAutomobile = 0;
        String modello = null;
        String marca = null;
        String carrozzeria = null;
        String alimentazione = null;
        int cilindrata = 0;
        int potenza = 0;
        int prezzo = 0;
        try {
            idAutomobile = Integer.valueOf(txtIdAutomobile.getText());
            modello = txtModello.getText();
            marca = txtMarca.getText();
            carrozzeria = txtCarrozzeria.getText();
            alimentazione = txtAlimentazione.getText();
            cilindrata = Integer.valueOf(txtCilindrata.getText());
            potenza = Integer.valueOf(txtPotenza.getText());
            prezzo = Integer.valueOf(txtPrezzo.getText());
            Automobile automobile = new Automobile(idAutomobile, modello, marca, carrozzeria, alimentazione, cilindrata, potenza, prezzo);
            listaauto.add(automobile);
            //txtaStampa.append(automobile.toString() + "\n");
            txtaStampa.setText("inserito!!!" + automobile.toString() + "\n");
        } catch (NumberFormatException numberFormatException) {
            txtaStampa.setText("Errore nei dati!!!\n");
        }
        stampa();
    }//GEN-LAST:event_bntInserisciActionPerformed

    private void stampa() {
        for (int i = 0; i < listaauto.size(); i++) {
            Automobile automobile = (Automobile) listaauto.get(i);
            txtaStampa.append(automobile.toString() + "\n");
        }
    }

    private void bntStampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStampaActionPerformed
        txtaStampa.setText("");
        stampa();
    }//GEN-LAST:event_bntStampaActionPerformed

    private void pulisci() {
        txtIdAutomobile.setText("");
        txtModello.setText("");
        txtMarca.setText("");
        txtCarrozzeria.setText("");
        txtAlimentazione.setText("");
        txtCilindrata.setText("");
        txtPotenza.setText("");
        txtPrezzo.setText("");
        txtaStampa.setText("");
    }

    private void btnPulisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulisciActionPerformed
        pulisci();
     }//GEN-LAST:event_btnPulisciActionPerformed

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        txtaStampa.setText("");
        int idAutomobile = Integer.valueOf(txtIdAutomobile.getText());

        for (int i = 0; i < listaauto.size(); i++) {
            Automobile automobile = (Automobile) listaauto.get(i);
            if (automobile.getIdAutomobile() == idAutomobile) {
                txtaStampa.append("trovato: " + automobile.toString() + "\n");

                txtIdAutomobile.setText(automobile.getIdAutomobile() + "");
                txtModello.setText(automobile.getModello());
                txtMarca.setText(automobile.getMarca());
                txtCarrozzeria.setText(automobile.getCarrozzeria());
                txtAlimentazione.setText(automobile.getAlimentazione());
                txtCilindrata.setText(automobile.getCilindrata() + "");
                txtPotenza.setText(automobile.getPotenza() + "");
                txtPrezzo.setText(automobile.getPrezzo() + "");
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellaActionPerformed
        txtaStampa.setText("");
        int idAutomobile = Integer.valueOf(txtIdAutomobile.getText());

        for (int i = listaauto.size() - 1; i >= 0; i--) {
            Automobile automobile = (Automobile) listaauto.get(i);
            if (automobile.getIdAutomobile() == idAutomobile) {
                listaauto.remove(i);
                txtaStampa.append("cancellato!!!" + automobile.toString() + "\n");
            }
        }
        stampa();
    }//GEN-LAST:event_btnCancellaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        txtaStampa.setText("");
        int idAutomobile = Integer.valueOf(txtIdAutomobile.getText());

        for (int i = 0; i < listaauto.size(); i++) {
            Automobile automobile = (Automobile) listaauto.get(i);
            if (automobile.getIdAutomobile() == idAutomobile) {

                try {
                    automobile.setIdAutomobile(Integer.valueOf(txtIdAutomobile.getText()));
                    automobile.setModello(txtModello.getText());
                    automobile.setMarca(txtMarca.getText());
                    automobile.setCarrozzeria(txtCarrozzeria.getText());
                    automobile.setAlimentazione(txtAlimentazione.getText());
                    automobile.setCilindrata(Integer.valueOf(txtCilindrata.getText()));
                    automobile.setPotenza(Integer.valueOf(txtPotenza.getText()));
                    automobile.setPrezzo(Integer.valueOf(txtPrezzo.getText()));
                    txtaStampa.append("modificato!! " + automobile.toString() + "\n");
                } catch (NumberFormatException numberFormatException) {
                    txtaStampa.setText("Errore nei dati!!!\n");

                }

            }
        }
        stampa();
    }//GEN-LAST:event_btnModificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRicercaAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntInserisci;
    private javax.swing.JButton bntStampa;
    private javax.swing.JButton btnCancella;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnPulisci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlimentazione;
    private javax.swing.JTextField txtCarrozzeria;
    private javax.swing.JTextField txtCilindrata;
    private javax.swing.JTextField txtIdAutomobile;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModello;
    private javax.swing.JTextField txtPotenza;
    private javax.swing.JTextField txtPrezzo;
    private javax.swing.JTextArea txtaStampa;
    // End of variables declaration//GEN-END:variables
}
