/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ricercaautoplus;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;
import nu.xom.ParsingException;

/**
 *
 * @author L14_00
 */
public class frmRicercaAutoPlus extends javax.swing.JFrame {

    /**
     * Creates new form frmRicercaAuto
     */
    ArrayList listaauto;
    int indice;

    public frmRicercaAutoPlus() {
        initComponents();
        listaauto = new ArrayList();
        indice = 0;
        pulisci();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdAutomobile = new javax.swing.JTextField();
        txtModello = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtCarrozzeria = new javax.swing.JTextField();
        txtAlimentazione = new javax.swing.JTextField();
        txtCilindrata = new javax.swing.JTextField();
        txtPotenza = new javax.swing.JTextField();
        txtPrezzo = new javax.swing.JTextField();
        bntInserisci = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaStampa = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bntStampa = new javax.swing.JButton();
        btnPulisci = new javax.swing.JButton();
        btnCerca = new javax.swing.JButton();
        btnCancella = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnCasuale = new javax.swing.JButton();
        bntDietro = new javax.swing.JButton();
        bntAvanti = new javax.swing.JButton();
        bntPrimo = new javax.swing.JButton();
        bntUltimo = new javax.swing.JButton();
        btnOrdina = new javax.swing.JButton();
        btnOrdinaABolle = new javax.swing.JButton();
        btnGeneraXML = new javax.swing.JButton();
        btnEsportaXML = new javax.swing.JButton();
        btnImportaXML = new javax.swing.JButton();
        btnSalvaSuFile = new javax.swing.JButton();
        btnApriDaFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdAutomobile.setText("txtIdAutomobile");

        txtModello.setText("txtModello");

        txtMarca.setText("txtMarca");

        txtCarrozzeria.setText("txtCarrozzeria");

        txtAlimentazione.setText("txtAlimentazione");

        txtCilindrata.setText("txtCilindrata");

        txtPotenza.setText("txtPotenza");

        txtPrezzo.setText("txtPrezzo");
        txtPrezzo.setVerifyInputWhenFocusTarget(false);

        bntInserisci.setText("Inserisci");
        bntInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInserisciActionPerformed(evt);
            }
        });

        txtaStampa.setColumns(20);
        txtaStampa.setRows(5);
        txtaStampa.setText("txtaStampa\n");
        jScrollPane1.setViewportView(txtaStampa);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("idAutomobile");

        jLabel2.setText("modello");

        jLabel3.setText("marca");

        jLabel4.setText("carrozzeria");

        jLabel5.setText("alimentazione");

        jLabel6.setText("cilindrata");

        jLabel7.setText("potenza");

        jLabel8.setText("prezzo");

        bntStampa.setText("Stampa");
        bntStampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntStampaActionPerformed(evt);
            }
        });

        btnPulisci.setText("Pulisci");
        btnPulisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulisciActionPerformed(evt);
            }
        });

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        btnCancella.setText("Cancella");
        btnCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellaActionPerformed(evt);
            }
        });

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        btnCasuale.setText("Casuale");
        btnCasuale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasualeActionPerformed(evt);
            }
        });

        bntDietro.setText("Dietro");
        bntDietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDietroActionPerformed(evt);
            }
        });

        bntAvanti.setText("Avanti");
        bntAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAvantiActionPerformed(evt);
            }
        });

        bntPrimo.setText("Primo");
        bntPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPrimoActionPerformed(evt);
            }
        });

        bntUltimo.setText("Ultimo");
        bntUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntUltimoActionPerformed(evt);
            }
        });

        btnOrdina.setText("Ordina");
        btnOrdina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdinaActionPerformed(evt);
            }
        });

        btnOrdinaABolle.setText("OrdinaABolle");
        btnOrdinaABolle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdinaABolleActionPerformed(evt);
            }
        });

        btnGeneraXML.setText("GeneraXML");
        btnGeneraXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraXMLActionPerformed(evt);
            }
        });

        btnEsportaXML.setText("EsportaXML");
        btnEsportaXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsportaXMLActionPerformed(evt);
            }
        });

        btnImportaXML.setText("ImportaXML");
        btnImportaXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportaXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPotenza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCilindrata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlimentazione, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarrozzeria, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdAutomobile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModello, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrezzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntStampa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOrdina)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrdinaABolle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImportaXML))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntInserisci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPulisci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancella)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCasuale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGeneraXML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnEsportaXML)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntDietro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntAvanti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntUltimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAutomobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntInserisci)
                    .addComponent(jLabel1)
                    .addComponent(btnPulisci)
                    .addComponent(btnCancella)
                    .addComponent(btnCasuale)
                    .addComponent(btnGeneraXML)
                    .addComponent(btnEsportaXML))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarrozzeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlimentazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPotenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntUltimo)
                            .addComponent(bntAvanti)
                            .addComponent(bntDietro)
                            .addComponent(bntPrimo))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntStampa)
                            .addComponent(btnCerca)
                            .addComponent(btnModifica)
                            .addComponent(btnOrdina)
                            .addComponent(btnOrdinaABolle)
                            .addComponent(btnImportaXML))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        btnSalvaSuFile.setText("SalvaSuFile");
        btnSalvaSuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaSuFileActionPerformed(evt);
            }
        });

        btnApriDaFile.setText("ApriDaFile");
        btnApriDaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApriDaFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvaSuFile)
                    .addComponent(btnApriDaFile))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnSalvaSuFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApriDaFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInserisciActionPerformed

        //txtaStampa.setText("ciao \n");
        int idAutomobile = 0;
        String modello = null;
        String marca = null;
        String carrozzeria = null;
        String alimentazione = null;
        int cilindrata = 0;
        int potenza = 0;
        int prezzo = 0;
        //MAX(idAutomobile)
        for (int i = 0; i < listaauto.size(); i++) {
            Automobile automobile = (Automobile) listaauto.get(i);
            if (automobile.getIdAutomobile() > idAutomobile) {
                idAutomobile = automobile.getIdAutomobile();
            }
        }
        idAutomobile++;

        try {
            //idAutomobile = Integer.valueOf(txtIdAutomobile.getText());
            txtIdAutomobile.setText(idAutomobile + "");
            modello = txtModello.getText();
            marca = txtMarca.getText();
            carrozzeria = txtCarrozzeria.getText();
            alimentazione = txtAlimentazione.getText();
            cilindrata = Integer.valueOf(txtCilindrata.getText());
            potenza = Integer.valueOf(txtPotenza.getText());
            prezzo = Integer.valueOf(txtPrezzo.getText());
            Automobile automobile = new Automobile(idAutomobile, modello, marca, carrozzeria, alimentazione, cilindrata, potenza, prezzo);
            listaauto.add(automobile);
            //txtaStampa.append(automobile.toString() + "\n");
            txtaStampa.setText("inserito!!!" + automobile.toString() + "\n");
        } catch (NumberFormatException numberFormatException) {
            txtaStampa.setText("Errore nei dati!!!\n");
        }
        stampa();
        indice = listaauto.size() - 1;
    }//GEN-LAST:event_bntInserisciActionPerformed

    private void stampa() {
        for (int i = 0; i < listaauto.size(); i++) {
            Automobile automobile = (Automobile) listaauto.get(i);
            txtaStampa.append(automobile.toString() + "\n");
        }
    }

    private void elemento(int indice) {
        Automobile automobile = (Automobile) listaauto.get(indice);
        txtIdAutomobile.setText(automobile.getIdAutomobile() + "");
        txtModello.setText(automobile.getModello());
        txtMarca.setText(automobile.getMarca());
        txtCarrozzeria.setText(automobile.getCarrozzeria());
        txtAlimentazione.setText(automobile.getAlimentazione());
        txtCilindrata.setText(automobile.getCilindrata() + "");
        txtPotenza.setText(automobile.getPotenza() + "");
        txtPrezzo.setText(automobile.getPrezzo() + "");
    }

    private void bntStampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStampaActionPerformed
        txtaStampa.setText("");
        stampa();
    }//GEN-LAST:event_bntStampaActionPerformed

    private void pulisci() {
        txtIdAutomobile.setText("");
        txtModello.setText("");
        txtMarca.setText("");
        txtCarrozzeria.setText("");
        txtAlimentazione.setText("");
        txtCilindrata.setText("");
        txtPotenza.setText("");
        txtPrezzo.setText("");
        txtaStampa.setText("");
    }

    private void btnPulisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulisciActionPerformed
        pulisci();
     }//GEN-LAST:event_btnPulisciActionPerformed

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        txtaStampa.setText("");
        int idAutomobile = Integer.valueOf(txtIdAutomobile.getText());

        for (int i = 0; i < listaauto.size(); i++) {
            Automobile automobile = (Automobile) listaauto.get(i);
            if (automobile.getIdAutomobile() == idAutomobile) {
                txtaStampa.append("trovato: " + automobile.toString() + "\n");

                txtIdAutomobile.setText(automobile.getIdAutomobile() + "");
                txtModello.setText(automobile.getModello());
                txtMarca.setText(automobile.getMarca());
                txtCarrozzeria.setText(automobile.getCarrozzeria());
                txtAlimentazione.setText(automobile.getAlimentazione());
                txtCilindrata.setText(automobile.getCilindrata() + "");
                txtPotenza.setText(automobile.getPotenza() + "");
                txtPrezzo.setText(automobile.getPrezzo() + "");
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellaActionPerformed
        txtaStampa.setText("");
        int idAutomobile = Integer.valueOf(txtIdAutomobile.getText());

        for (int i = listaauto.size() - 1; i >= 0; i--) {
            Automobile automobile = (Automobile) listaauto.get(i);
            if (automobile.getIdAutomobile() == idAutomobile) {
                listaauto.remove(i);
                txtaStampa.append("cancellato!!!" + automobile.toString() + "\n");
            }
        }
        stampa();
    }//GEN-LAST:event_btnCancellaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        txtaStampa.setText("");
        int idAutomobile = Integer.valueOf(txtIdAutomobile.getText());

        for (int i = 0; i < listaauto.size(); i++) {
            Automobile automobile = (Automobile) listaauto.get(i);
            if (automobile.getIdAutomobile() == idAutomobile) {

                try {
                    automobile.setIdAutomobile(Integer.valueOf(txtIdAutomobile.getText()));
                    automobile.setModello(txtModello.getText());
                    automobile.setMarca(txtMarca.getText());
                    automobile.setCarrozzeria(txtCarrozzeria.getText());
                    automobile.setAlimentazione(txtAlimentazione.getText());
                    automobile.setCilindrata(Integer.valueOf(txtCilindrata.getText()));
                    automobile.setPotenza(Integer.valueOf(txtPotenza.getText()));
                    automobile.setPrezzo(Integer.valueOf(txtPrezzo.getText()));
                    txtaStampa.append("modificato!! " + automobile.toString() + "\n");
                } catch (NumberFormatException numberFormatException) {
                    txtaStampa.setText("Errore nei dati!!!\n");

                }

            }
        }
        stampa();
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnCasualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasualeActionPerformed
        Random random = new Random();
        int i;
        if (listaauto.size() > 0) {
            i = random.nextInt(listaauto.size());
            Automobile automobile = (Automobile) listaauto.get(i);
            txtaStampa.append("trovato!! " + automobile.toString() + "\n");

            txtIdAutomobile.setText(automobile.getIdAutomobile() + "");
            txtModello.setText(automobile.getModello());
            txtMarca.setText(automobile.getMarca());
            txtCarrozzeria.setText(automobile.getCarrozzeria());
            txtAlimentazione.setText(automobile.getAlimentazione());
            txtCilindrata.setText(automobile.getCilindrata() + "");
            txtPotenza.setText(automobile.getPotenza() + "");
            txtPrezzo.setText(automobile.getPrezzo() + "");
            stampa();
        }
    }//GEN-LAST:event_btnCasualeActionPerformed

    private void bntDietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDietroActionPerformed
        if (indice > 0) {
            indice--;
        }
        elemento(indice);
    }//GEN-LAST:event_bntDietroActionPerformed

    private void bntAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAvantiActionPerformed
        if (indice < listaauto.size() - 1) {
            indice++;
        }
        elemento(indice);
    }//GEN-LAST:event_bntAvantiActionPerformed

    private void bntPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPrimoActionPerformed
        indice = 0;
        elemento(indice);
    }//GEN-LAST:event_bntPrimoActionPerformed

    private void bntUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntUltimoActionPerformed
        indice = listaauto.size() - 1;
        elemento(indice);
    }//GEN-LAST:event_bntUltimoActionPerformed

    private void btnOrdinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdinaActionPerformed
        //listaauto.sort(c);
        txtaStampa.setText("");
        Collections.sort(listaauto);
        stampa();
        indice = 0;
        elemento(indice);
    }//GEN-LAST:event_btnOrdinaActionPerformed

    private void btnOrdinaABolleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdinaABolleActionPerformed
        //listaauto.sort(c);
        txtaStampa.setText("");
        int n = listaauto.size();
        for (int i = 0; i < n; i++) {
            for (int j = 1; j < (n - i); j++) {
                Automobile automobilep = (Automobile) listaauto.get(j - 1);
                Automobile automobiled = (Automobile) listaauto.get(j);
                //if (automobilep.getIdAutomobile() < automobiled.getIdAutomobile()) {
                int compa;
                compa = automobilep.getMarca().compareTo(automobiled.getMarca());
                if (compa == 0) {
                    compa = automobilep.getModello().compareTo(automobiled.getModello());
                }
                if (compa > 0) {
                    listaauto.set(j - 1, automobiled);
                    listaauto.set(j, automobilep);
                }
            }
        }
        stampa();
        indice = 0;
        elemento(indice);
    }//GEN-LAST:event_btnOrdinaABolleActionPerformed

    private void btnGeneraXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraXMLActionPerformed
        txtaStampa.setText("<?xml version=\"1.0\"?> \n");
        txtaStampa.append("<ricercauto>   \n");
        for (int i = 0; i < listaauto.size(); i++) {
            txtaStampa.append("  <automobile>   \n");
            Automobile automobile = (Automobile) listaauto.get(i);
            txtaStampa.append("    <idautomobile>" + automobile.getIdAutomobile() + "</idautomobile> \n");
            txtaStampa.append("    <modello>" + automobile.getModello() + "</modello> \n");
            txtaStampa.append("    <marca>" + automobile.getMarca() + "</marca> \n");
            txtaStampa.append("    <carrozzeria>" + automobile.getCarrozzeria() + "</carrozzeria> \n");
            txtaStampa.append("    <alimentazione>" + automobile.getAlimentazione() + "</alimentazione> \n");
            txtaStampa.append("    <cilindrata>" + automobile.getCilindrata() + "</cilindrata> \n");
            txtaStampa.append("    <potenza>" + automobile.getPotenza() + "</potenza> \n");
            txtaStampa.append("    <prezzo>" + automobile.getPrezzo() + "</prezzo> \n");
            txtaStampa.append("  </automobile>   \n");
        }
        txtaStampa.append("</ricercauto>   \n");
    }//GEN-LAST:event_btnGeneraXMLActionPerformed

    private void btnEsportaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsportaXMLActionPerformed
        // TODO add your handling code here:

        Element ricercaauto = new Element("ricercaauto");
        for (int i = 0; i < listaauto.size(); i++) {
            Element automobile = new Element("automobile");
            Automobile auto = (Automobile) listaauto.get(i);

            Element idautomobile = new Element("idautomobile");
            idautomobile.appendChild(auto.getIdAutomobile() + "");
            Element modello = new Element("modello");
            modello.appendChild(auto.getModello());
            Element marca = new Element("marca");
            marca.appendChild(auto.getMarca());
            Element carrozzeria = new Element("carrozzeria");
            carrozzeria.appendChild(auto.getCarrozzeria());
            Element alimentazione = new Element("alimentazione");
            alimentazione.appendChild(auto.getAlimentazione());
            Element cilindrata = new Element("cilindrata");
            cilindrata.appendChild(auto.getCilindrata() + "");
            Element potenza = new Element("potenza");
            potenza.appendChild(auto.getPotenza() + "");
            Element prezzo = new Element("prezzo");
            prezzo.appendChild(auto.getPrezzo() + "");

            automobile.appendChild(idautomobile);
            automobile.appendChild(modello);
            automobile.appendChild(marca);
            automobile.appendChild(carrozzeria);
            automobile.appendChild(alimentazione);
            automobile.appendChild(cilindrata);
            automobile.appendChild(potenza);
            automobile.appendChild(prezzo);

            ricercaauto.appendChild(automobile);
        }
        Document doc = new Document(ricercaauto);
        txtaStampa.setText(doc.toXML());
    }//GEN-LAST:event_btnEsportaXMLActionPerformed

    private void btnImportaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportaXMLActionPerformed
        Builder builder = new Builder();
        try {
            Document doc = builder.build(new StringReader(txtaStampa.getText()));
            txtaStampa.setText("");
            Element ricercaauto = doc.getRootElement();
            Elements automobili = ricercaauto.getChildElements("automobile");
            for (int i = 0; i < automobili.size(); i++) {
                Element automobile = automobili.get(i);
                Element idautomobile = automobile.getFirstChildElement("idautomobile");
                Element modello = automobile.getFirstChildElement("modello");
                Element marca = automobile.getFirstChildElement("marca");
                Element carrozzeria = automobile.getFirstChildElement("carrozzeria");
                Element alimentazione = automobile.getFirstChildElement("alimentazione");
                Element cilindrata = automobile.getFirstChildElement("cilindrata");
                Element potenza = automobile.getFirstChildElement("potenza");
                Element prezzo = automobile.getFirstChildElement("prezzo");

                listaauto.add(new Automobile(idautomobile, modello, marca, carrozzeria, alimentazione, cilindrata, potenza, prezzo));
                //listaauto.add(new Automobile(Integer.valueOf(idautomobile.getValue()), modello.getValue(), marca.getValue(), carrozzeria.getValue(), alimentazione.getValue(), Integer.valueOf(cilindrata.getValue()), Integer.valueOf(potenza.getValue()), Integer.valueOf(prezzo.getValue())));
            }
        } catch (ParsingException ex) {
            Logger.getLogger(frmRicercaAutoPlus.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmRicercaAutoPlus.class.getName()).log(Level.SEVERE, null, ex);
        }
        stampa();
    }//GEN-LAST:event_btnImportaXMLActionPerformed

    private void btnSalvaSuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaSuFileActionPerformed
        //FileWriter fileWriter = new FileWriter("c:\\prova\\MiaAgenda.txt", true);            
        try {
            FileWriter fileWriter = new FileWriter("MiaRicercaAuto.txt", false);
            PrintWriter printWriter = new PrintWriter(fileWriter);
            printWriter.print(txtaStampa.getText());
            printWriter.close();
            fileWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(frmRicercaAutoPlus.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSalvaSuFileActionPerformed

    private void btnApriDaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApriDaFileActionPerformed
        txtaStampa.setText("");
        try  {
            FileReader fileReader = new FileReader("MiaRicercaAuto.txt");
            int data = fileReader.read();
            while (data != -1) {
                txtaStampa.append(""+(char)data);
                data = fileReader.read();
            }
        } catch (IOException ex) {
            Logger.getLogger(frmRicercaAutoPlus.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnApriDaFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAutoPlus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAutoPlus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAutoPlus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRicercaAutoPlus.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRicercaAutoPlus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAvanti;
    private javax.swing.JButton bntDietro;
    private javax.swing.JButton bntInserisci;
    private javax.swing.JButton bntPrimo;
    private javax.swing.JButton bntStampa;
    private javax.swing.JButton bntUltimo;
    private javax.swing.JButton btnApriDaFile;
    private javax.swing.JButton btnCancella;
    private javax.swing.JButton btnCasuale;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnEsportaXML;
    private javax.swing.JButton btnGeneraXML;
    private javax.swing.JButton btnImportaXML;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnOrdina;
    private javax.swing.JButton btnOrdinaABolle;
    private javax.swing.JButton btnPulisci;
    private javax.swing.JButton btnSalvaSuFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlimentazione;
    private javax.swing.JTextField txtCarrozzeria;
    private javax.swing.JTextField txtCilindrata;
    private javax.swing.JTextField txtIdAutomobile;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModello;
    private javax.swing.JTextField txtPotenza;
    private javax.swing.JTextField txtPrezzo;
    private javax.swing.JTextArea txtaStampa;
    // End of variables declaration//GEN-END:variables
}
